# Generated by Django 4.2.6 on 2024-04-20 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_customuser_contacto_customuser_direccion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="direccion",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="contacto",
            new_name="contact",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="encargado",
            new_name="manager",
        ),
    ]
