# Generated by Django 4.2.6 on 2024-05-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
    ]
