# Generated by Django 4.2.6 on 2024-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='global_pending',
            field=models.BooleanField(default=False),
        ),
    ]
