# Generated by Django 4.2.6 on 2024-05-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_global_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_pending',
        ),
        migrations.AlterField(
            model_name='product',
            name='global_pending',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
